{
 "title": "Обращения: детализация",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "domain_id", "query": "${VAR_DOMAIN_ID}" },
   { "name": "ticket_id", "query": "${VAR_TICKET_ID}" },
   {
    "name": "ticket_text_html",
    "query": "select description __value, subject __text\nfrom fresh.ticket\nwhere domain_id = $domain_id\n  and id = $ticket_id"
   },
   { "name": "access_token", "query": "${VAR_ACCESS_TOKEN}" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>${ticket_text_html:text}</h1>\n\n${ticket_text_html:raw}\n\n"
   }
  },
  {
   "title": "Вложения",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "with attachments as (\n  select unnest(attachment_ids) attachment_ids\n  from (\n    select attachment_ids\n    from fresh.ticket\n    where domain_id = $domain_id \n      and id = $ticket_id\n\n    union all\n\n    select attachment_ids\n    from fresh.conversation \n    where domain_id = $domain_id\n      and ticket_id = $ticket_id \n  ) x\n)\n\nselect id, name \"Имя\", pg_size_pretty(file_size) \"Размер\", domain_id\nfrom fresh.attachment\nwhere domain_id = $domain_id\n  and id in (select attachment_ids from attachments)"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select t.created_at \"Создано\"\n  , t.archived \"Архив\"\n  , t.is_escalated \"Escalated\"\n  , t.due_by \"Due by\"\n  , t.fr_due_by \"FR due by\"\n  , t.fr_escalated \"FR Escalated\"\n  , p.name \"Приоритет\"\n  , s.name \"Статус\"\n  , so.name \"Канал\"\n  , t.type \"Тип\"\n  --, t.subject \"Тема\"\n  , agg.tags \"Теги\"\n  , t.requester_name \"Клиент\"\n  , agg.fwd_emails \"FWD emails\"\n  --, t.description_text \"Обращение\"\n  , t.id\nfrom fresh.ticket t\n  left join fresh.ticket_priority p on p.value = t.priority\n  left join fresh.ticket_status s on s.value = t.status\n  left join fresh.ticket_source so on so.value = t.source\n  left join lateral (\n    select array_to_string(t.tags, ', ') tags\n      , array_to_string(t.fwd_emails, ', ') fwd_emails\n  ) agg on true\nwhere t.domain_id = $domain_id \n  and t.id = $ticket_id\norder by 1 desc"
    }
   ]
  },
  {
   "title": "Пользовательские поля",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select x.key \"Имя\"\n  , x.value \"Значение\"\nfrom fresh.ticket t\n  left join lateral jsonb_each_text(t.custom_fields) x on true\nwhere t.domain_id = $domain_id\n  and t.id = $ticket_id  \n  and x.value notnull"
    }
   ]
  },
  {
   "title": "Сообщения",
   "type": "table",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 11 },
   "targets": [
    {
     "rawSql": "select c.created_at \"Создано\"\n  , cc.name \"Источник\"\n  , c.from_email \"От\"\n  , agg.to_emails \"Кому\"\n  , c.body_text \"Текст\"\n  , c.incoming \"Входящее\"\n  , c.private \"Приватное\"\n  , c.id\nfrom fresh.conversation c\n  left join fresh.conversation_source cc on c.source = cc.value\n  left join lateral (\n    select array_to_string(c.to_emails, ', ') to_emails\n  ) agg on true\nwhere c.domain_id = $domain_id\n  and c.ticket_id = $ticket_id\norder by 1 asc"
    }
   ]
  }
 ]
}